### PR TITLE
Prerelease v1.0.0-alpha.8

### PR DESCRIPTION
**Pull request by shuming1998**

### CODE REVIEW

**Review by Pythonzhai — APPROVED** [review]

**Comment by shuming1998** [comment]
Pull request #9  has files with unformatted code:
M lib.js
 M package.json

**Comment by shuming1998** [comment]
Pull request #9  has files with unformatted code:
M lib.js
 M package.json

**Comment by shuming1998** [comment]
---Pull request #9  has files with unformatted code---
M lib.js
 M package.json
[Please standardize the codes format]

**Comment by shuming1998** [comment]
---Pull request #9  has files with unformatted code---
M lib.js
 M package.json
---Please standardize the codes format---

**Comment by shuming1998** [comment]
---Pull request #9  has files with unformatted code---
M lib.js
 M package.json
---Please ensure the codes formatted---

**Pull request merged**
